name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Restore cached Node.js modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: node-${{ hashFiles('package-lock.json') }}

      - name: Install Node.js modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run-script build
